<div class="alert alert-block alert-info">
<center>MÉTODOS NUMÉRICOS</center>
<center>LISTA 10</center>
<center>ALUNO: JONATAS DA SILVA DUARTE</center>
</div>


In [1]:
import numpy as np
import random as rn
import matplotlib.pyplot as plt
import scipy.linalg as sla

np.__version__

'1.20.1'

1. Classifique os sistemas abaixo com relação a quantidade e existência de soluções.

In [2]:
## 1°
a =  np.array([[1,2,3],[4,5,6],[7,8,9]])
b =  np.array([1,1,1])

## Rank(A)
np.linalg.matrix_rank(a)

2

In [3]:
## Rank (Ã)
np.linalg.matrix_rank(np.c_[a, b])

2

In [4]:
a.shape[1]

3

In [5]:
## 2°
c = np.array([[2,3],[-4,-6]])
d = np.array([10,-10])

## Rank(A)
np.linalg.matrix_rank(c)

1

In [6]:
## Rank (Ã)
np.linalg.matrix_rank(np.c_[c, d])

2

In [7]:
c.shape[1]

2

Assim, 1° sistema é possível e indeterminado (rank(Ã) = rank(A) < n). 

Enquanto o 2° é um sistema imposssível (rank(Ã) > rank(A))

2. Repita o exemplo 3.2 acima, porém fazendo cada passo da execução de forma explícita

In [8]:
e = np.array([[3, 4, -5, 1],[0, 1, 1, -2],[0, 0, 4, -5], [0, 0, 0, 2]])
f = np.array([-10, -1, 3, 2])

In [9]:
## Passo 1
n = e.shape[1]
x = np.empty(n)

In [10]:
## Passo 2
x[-1] = f[-1]/e[-1, -1]
x

array([ 2.,  3., -4.,  1.])

In [11]:
## Passo 3
for i in range(n-2, -1, -1):
    print(np.sum(e[i,i+1:]*x[i+1:]))

-5.0
-6.0
33.0


In [12]:
## Passo 4
for i in range(n-2, -1, -1):
    x[i] = (f[i] - np.sum(e[i,i+1:]*x[i+1:]))/e[i,i]
x

array([ 1., -1.,  2.,  1.])

In [13]:
## Fazendo a comparação
def sist_lin_tri_sup(A,b):
    n = len(b)
    x = np.empty(n)
    x[-1] = b[-1]/A[-1, -1]
    for i in range(n-2, -1, -1):
        x[i] = (b[i] - np.sum(A[i,i+1:]*x[i+1:]))/A[i,i]
    return x

    
sist_lin_tri_sup(e,f)

array([ 1., -1.,  2.,  1.])

Assim, conseguimos reproduzir passo a passo e obter os mesmos resultados.

3. Repita o exemplo 3.3 acima, porém fazendo cada passo da execução de forma explícita

In [14]:
## Passo 1 - feito
A = np.array([[3,0,0,0],[2,1,0,0],[1,0,1,0],[1,1,1,1]])
B = np.array([4,2,4,2])

n = A.shape[1]
x = np.empty(n)

In [15]:
## Passo 2
x[0] = B[0]/A[0, 0]
x[0]

1.3333333333333333

In [16]:
## Passo 3
for i in range(1, n):
    print(np.sum(A[i,:i]*x[:i]))

2.6666666666666665
1.3333333333333333
4.333333333333333


In [17]:
## Passo 4
for i in range(1,n):
    x[i] = (B[i] - np.sum(A[i,:i]*x[:i]))/A[i,i]
x

array([ 1.33333333, -0.66666667,  2.66666667, -1.33333333])

In [18]:
## Comparação
def sist_lin_tri_inf(A,b):
    n = len(b)
    x = np.empty(n)
    x[0] = b[0]/A[0, 0]
    for i in range(1,n):
        x[i] = (b[i] - np.sum(A[i,:i]*x[:i]))/A[i,i]
    return x

sist_lin_tri_inf(A,B)

array([ 1.33333333, -0.66666667,  2.66666667, -1.33333333])

Assim como a anterior.

4. Implemente uma função, cujos parâmetros de entrada sejam somente a matriz de coeficientes e o vetor de termos independentes e que calcule o vetor solução para qualquer um dos casos triviais vistos aqui. 

In [19]:
## P/ dividir a tarefa, usaremos uma função que verifica a diagonal principal (superior ou inferior)
def verifica_diagonal(matriz, tipo):
    tt = 0
    
    for lin in range(matriz.shape[1]):
        for col in range(matriz.shape[1]):
            if (tipo == "inf" and col>lin):
                tt += matriz[lin][col]
                
            elif (tipo == "sup" and col<lin):
                tt += matriz[lin][col]                
    return tt

In [20]:
## Função principal
def vetor_solucao(matriz, termos):
    ## Verifica se o sistema tem solução precisa
    if (np.linalg.matrix_rank(np.c_[matriz, termos]) > np.linalg.matrix_rank(matriz)):
        return ("sistema não admite uma solução precisa")
    else:
        ## Usamos nossa funnção de apoio para verificar a diagonal
        soma_sup = verifica_diagonal(matriz, "inf")
        soma_inf = verifica_diagonal(matriz, "sup")
        if (soma_sup == 0):
            vetor_sol = sla.solve_triangular(matriz, termos, lower=True)
        elif (soma_inf == 0):
            vetor_sol = sla.solve_triangular(matriz, termos, lower=False)
        else:
            vetor_sol = sist_lin_tri_inf(matriz, termos)
    return vetor_sol        

In [21]:
## Usando as matrizess dadas antes, temos: 1° situação
print('Matriz:\n',a,'\nTermos:\n',b)
vetor_solucao(a,b)

Matriz:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
Termos:
 [1 1 1]


array([ 1.        , -0.6       , -0.13333333])

In [22]:
## 2° situação
print('Matriz:\n',c,'\nTermos:\n',d)
vetor_solucao(c,d)

Matriz:
 [[ 2  3]
 [-4 -6]] 
Termos:
 [ 10 -10]


'sistema não admite uma solução precisa'

In [23]:
## 3° situacao
print('Matriz:\n',e,'\nTermos:\n',f)
vetor_solucao(e,f)

Matriz:
 [[ 3  4 -5  1]
 [ 0  1  1 -2]
 [ 0  0  4 -5]
 [ 0  0  0  2]] 
Termos:
 [-10  -1   3   2]


array([ 1., -1.,  2.,  1.])

In [24]:
## 4° situacao
print('Matriz:\n',A,'\nTermos:\n',B)
vetor_solucao(A,B)

Matriz:
 [[3 0 0 0]
 [2 1 0 0]
 [1 0 1 0]
 [1 1 1 1]] 
Termos:
 [4 2 4 2]


array([ 1.33333333, -0.66666667,  2.66666667, -1.33333333])